### ISSUE TITLE
requirements.txt and LICENSE files missing in the source distribution on PyPI

### ISSUE THREAD

**Issue by giswqs** [paperswithcode/model-index#6]
The source distribution of this package on PyPI does not include the LICENSE and requirements.txt files. It would be great to add them in the next release.

**Comment by giswqs** [comment]
@rstojnic @RJT1990 @datumbox Can you create a tag release on GitHub so that conda-forge can pull the source code from GitHub? The PyPI missed the requirements.txt and LICENSE files

**Comment by giswqs** [comment]
I am trying to add `model-index` to conda-forge. 
https://github.com/conda-forge/staged-recipes/pull/21737

**Comment by hubutui** [comment]
It seems that this issue is not resolved yet. And there is no tag in github repo.
